// source/prfs_web/src/layouts/default_layout/DefaultLayout.tsx
"use client";

import React from "react";

import styles from "./DefaultLayout.module.scss";
import Masthead from "@/components/masthead/Masthead";
import LeftBar from "@/components/left_bar/LeftBar";
import { i18nContext } from "@/contexts/i18n";

const DefaultLayout: React.FC<DefaultLayoutProps> = ({ children }) => {
  const i18n = React.useContext(i18nContext);

  return (
    <div className={styles.wrapper}>
      <Masthead />
      <div className={styles.main}>
        <div className={styles.leftBarContainer}>
          <LeftBar />
        </div>
        <div className={styles.contentArea}>
          <div>{children}</div>
        </div>
      </div>
    </div>
  );
};

export default DefaultLayout;

export interface DefaultLayoutProps {
  children: React.ReactNode;
}

// source/prfs_sdk_web_ui_solidjs/src/layouts/default_layout/DefaultLayout.tsx
import type { Component, JSX } from "solid-js";
import { useContext } from "solid-js";

import styles from "./DefaultLayout.module.scss";
import { I18nContext } from "@/contexts/i18n";

const DefaultLayout: Component<DefaultLayoutProps> = ({ children }) => {
  const i18n = useContext(I18nContext);

  return (
    <div class={styles.wrapper}>
      <div>{children}</div>
      <div class={styles.powered}>{i18n.powered_by_prfs_web_sdk}</div>
    </div>
  );
};

export default DefaultLayout;

export interface DefaultLayoutProps {
  children: JSX.Element;
}
