// source/prfs_react_components/src/button/Button.tsx
import React, { MouseEventHandler } from "react";
import classnames from "classnames";

import styles from "./Button.module.scss";

const Button: React.FC<Button1Props> = ({
  children,
  className,
  handleClick,
  variant,
  disabled,
}) => {
  return (
    <button
      className={classnames({
        [styles.a]: variant === "a",
        [styles.b]: variant === "b",
        [styles.c]: variant === "c",
        [styles.transparent_a]: variant === "transparent_a",
        [styles.text_c]: variant === "text_c",
        [className || ""]: true,
      })}
      onClick={handleClick}
      disabled={!!disabled}
    >
      {children}
    </button>
  );
};

export default Button;

export interface Button1Props {
  variant: "a" | "b" | "c" | "transparent_a" | "text_c";
  className?: string;
  children: React.ReactNode;
  disabled?: boolean;
  handleClick?: MouseEventHandler;
}

// source/prfs_sdk_web_ui_solidjs/src/components/button/Button.tsx
import { Component, JSX } from "solid-js";
import classnames from "classnames";

import styles from "./Button.module.scss";

const Button: Component<Button1Props> = ({ children, handleClick, variant }) => {
  return (
    <button
      class={classnames({
        [styles.a]: variant === "a",
        [styles.b]: variant === "b",
        [styles.transparent_a]: variant === "transparent_a",
      })}
      onClick={handleClick}
    >
      {children}
    </button>
  );
};

export default Button;

export interface Button1Props {
  variant: "a" | "b" | "transparent_a";
  children: JSX.Element;
  handleClick?: JSX.EventHandlerUnion<any, MouseEvent>;
}
